// Dinner Randomizer V1 restaurant database
// pricePerPerson and distance are prototype planning estimates.
// We will replace these with live location / restaurant data in a later version.

export const restaurants = [
  {
    name: "Gloria's Latin Cuisine",
    cuisine: "Mexican",
    pricePerPerson: 25,
    distance: 2,
    favorite: true,
    status: "Favorite",
  },
  {
    name: "Anamia's Tex Mex",
    cuisine: "Mexican",
    pricePerPerson: 25,
    distance: 2,
    favorite: false,
    status: "Keep",
  },
  {
    name: "Chipotle Mexican Grill",
    cuisine: "Mexican",
    pricePerPerson: 15,
    distance: 4,
    favorite: false,
    status: "Keep",
  },
  {
    name: "Ernesto's",
    cuisine: "Mexican",
    pricePerPerson: 20,
    distance: 1,
    favorite: false,
    status: "Keep",
  },
  {
    name: "LaLa's Taqueria",
    cuisine: "Mexican",
    pricePerPerson: 15,
    distance: 2,
    favorite: false,
    status: "Keep",
  },
  {
    name: "Mi Luna Great Tex-Mex",
    cuisine: "Mexican",
    pricePerPerson: 25,
    distance: 2,
    favorite: false,
    status: "Don't know it",
  },
  {
    name: "Torchy's Tacos",
    cuisine: "Mexican",
    pricePerPerson: 18,
    distance: 4,
    favorite: false,
    status: "Keep",
  },
  {
    name: "Uncle Julio's",
    cuisine: "Mexican",
    pricePerPerson: 30,
    distance: 12,
    favorite: false,
    status: "Keep",
  },

  {
    name: "Maggiano's Little Italy",
    cuisine: "Italian",
    pricePerPerson: 35,
    distance: 14.7,
    favorite: true,
    status: "Favorite",
  },
  {
    name: "Olive Garden Italian Restaurant",
    cuisine: "Italian",
    pricePerPerson: 25,
    distance: 2,
    favorite: true,
    status: "Favorite",
  },
  {
    name: "Capo's Pizza And Pasta",
    cuisine: "Italian",
    pricePerPerson: 20,
    distance: 2,
    favorite: false,
    status: "Don't know it",
  },
  {
    name: "Eddies Napoli Italian Bistro",
    cuisine: "Italian",
    pricePerPerson: 25,
    distance: 2,
    favorite: false,
    status: "Keep",
  },
  {
    name: "Piada Italian Street Food",
    cuisine: "Italian",
    pricePerPerson: 18,
    distance: 10,
    favorite: false,
    status: "Keep",
  },
  {
    name: "Roma's Italian Restaurant",
    cuisine: "Italian",
    pricePerPerson: 25,
    distance: 2,
    favorite: false,
    status: "Don't know it",
  },
  {
    name: "Salute Italian Restaurant - Prosper",
    cuisine: "Italian",
    pricePerPerson: 35,
    distance: 2,
    favorite: false,
    status: "Keep",
  },

  {
    name: "Hana Hibachi & Sushi",
    cuisine: "Japanese",
    pricePerPerson: 25,
    distance: 2,
    favorite: true,
    status: "Favorite",
  },
  {
    name: "Hibachi Master",
    cuisine: "Japanese",
    pricePerPerson: 18,
    distance: 2,
    favorite: true,
    status: "Favorite",
  },
  {
    name: "Koishi Ramen & Sushi Bar",
    cuisine: "Japanese",
    pricePerPerson: 25,
    distance: 2,
    favorite: false,
    status: "Don't know it",
  },
  {
    name: "Sake Sushi Hibachi Steakhouse",
    cuisine: "Japanese",
    pricePerPerson: 30,
    distance: 2,
    favorite: false,
    status: "Don't know it",
  },
  {
    name: "Sushi Bene",
    cuisine: "Japanese",
    pricePerPerson: 30,
    distance: 2,
    favorite: false,
    status: "Don't know it",
  },

  {
    name: "88 Bao Bao",
    cuisine: "Chinese",
    pricePerPerson: 20,
    distance: 10,
    favorite: false,
    status: "Keep",
  },
  {
    name: "Dumpling House",
    cuisine: "Chinese",
    pricePerPerson: 22,
    distance: 10,
    favorite: false,
    status: "Keep",
  },
  {
    name: "P.F. Chang's",
    cuisine: "Chinese",
    pricePerPerson: 30,
    distance: 12,
    favorite: false,
    status: "Keep",
  },
  {
    name: "Panda Express",
    cuisine: "Chinese",
    pricePerPerson: 15,
    distance: 2,
    favorite: false,
    status: "Keep",
  },
  {
    name: "Pei Wei Asian Kitchen",
    cuisine: "Chinese",
    pricePerPerson: 20,
    distance: 2,
    favorite: false,
    status: "Keep",
  },
  {
    name: "Tapan Wok",
    cuisine: "Chinese",
    pricePerPerson: 20,
    distance: 2,
    favorite: false,
    status: "Keep",
  },
  {
    name: "The Chinese Neighbor",
    cuisine: "Chinese",
    pricePerPerson: 18,
    distance: 2,
    favorite: false,
    status: "Keep",
  },  
  {
    name: "Khun Nye Thai",
    cuisine: "Thai",
    pricePerPerson: 20,
    distance: 2,
    favorite: false,
    status: "Don't know it",
  },
  {
    name: "Manee Thai Cuisine & Bar",
    cuisine: "Thai",
    pricePerPerson: 22,
    distance: 10,
    favorite: false,
    status: "Don't know it",
  },
  {
    name: "Sabaidee Lao & Thai Street Food",
    cuisine: "Thai",
    pricePerPerson: 18,
    distance: 2,
    favorite: false,
    status: "Don't know it",
  },
  {
    name: "Thai Charm Frisco",
    cuisine: "Thai",
    pricePerPerson: 25,
    distance: 10,
    favorite: false,
    status: "Don't know it",
  },
  {
    name: "Thai360",
    cuisine: "Thai",
    pricePerPerson: 20,
    distance: 2,
    favorite: false,
    status: "Don't know it",
  },

  {
    name: "Hyderabad House - Prosper",
    cuisine: "Indian",
    pricePerPerson: 20,
    distance: 3,
    favorite: false,
    status: "Don't know it",
  },
  {
    name: "Jatara Indian Kitchen",
    cuisine: "Indian",
    pricePerPerson: 22,
    distance: 2,
    favorite: false,
    status: "Don't know it",
  },
  {
    name: "Nag's Kitchen",
    cuisine: "Indian",
    pricePerPerson: 20,
    distance: 3,
    favorite: false,
    status: "Don't know it",
  },
  {
    name: "Raasa Restaurant & Bar",
    cuisine: "Indian",
    pricePerPerson: 30,
    distance: 2,
    favorite: false,
    status: "Don't know it",
  },
  {
    name: "Sai Bhavan",
    cuisine: "Indian",
    pricePerPerson: 20,
    distance: 2,
    favorite: false,
    status: "Don't know it",
  },

  {
    name: "Burning Rice",
    cuisine: "Korean",
    pricePerPerson: 20,
    distance: 9,
    favorite: true,
    status: "Favorite",
  },
  {
    name: "88 Korean BBQ & Hot Pot",
    cuisine: "Korean",
    pricePerPerson: 35,
    distance: 11,
    favorite: false,
    status: "Keep",
  },
  {
    name: "Chicken Barn Korean Style Cuisine",
    cuisine: "Korean",
    pricePerPerson: 25,
    distance: 10,
    favorite: false,
    status: "Don't know it",
  },
  {
    name: "Goyaki",
    cuisine: "Korean",
    pricePerPerson: 20,
    distance: 2,
    favorite: false,
    status: "Don't know it",
  },
  {
    name: "Mama's Korean Kitchen",
    cuisine: "Korean",
    pricePerPerson: 25,
    distance: 8,
    favorite: false,
    status: "Don't know it",
  },

  {
    name: "I Love Pho",
    cuisine: "Vietnamese",
    pricePerPerson: 18,
    distance: 10,
    favorite: true,
    status: "Favorite",
  },
  {
    name: "Texas Pho House",
    cuisine: "Vietnamese",
    pricePerPerson: 20,
    distance: 9,
    favorite: false,
    status: "Keep",
  },
  {
    name: "Ginger & Spice Vietnamese Kitchen",
    cuisine: "Vietnamese",
    pricePerPerson: 20,
    distance: 2,
    favorite: false,
    status: "Don't know it",
  },
  {
    name: "Phoke Noodles & Grill",
    cuisine: "Vietnamese",
    pricePerPerson: 20,
    distance: 2,
    favorite: false,
    status: "Don't know it",
  },
  {
    name: "Pho Que Huong Noodle & Grill",
    cuisine: "Vietnamese",
    pricePerPerson: 18,
    distance: 9,
    favorite: false,
    status: "Don't know it",
  },

  {
    name: "Platia Greek Kouzina",
    cuisine: "Mediterranean",
    pricePerPerson: 30,
    distance: 10,
    favorite: true,
    status: "Favorite",
  },
  {
    name: "Fadi's Mediterranean Grill",
    cuisine: "Mediterranean",
    pricePerPerson: 25,
    distance: 10,
    favorite: false,
    status: "Keep",
  },
  {
    name: "Hungry Platters & Gyro",
    cuisine: "Mediterranean",
    pricePerPerson: 18,
    distance: 5,
    favorite: false,
    status: "Keep",
  },
  {
    name: "Spitz Mediterranean Street Food",
    cuisine: "Mediterranean",
    pricePerPerson: 18,
    distance: 2,
    favorite: false,
    status: "Keep",
  },
  {
    name: "The Halal Guys",
    cuisine: "Mediterranean",
    pricePerPerson: 20,
    distance: 5,
    favorite: false,
    status: "Keep",
  },  
  {
    name: "J. Alexander's",
    cuisine: "Steak & Grill",
    pricePerPerson: 45,
    distance: 4,
    favorite: true,
    status: "Favorite",
  },
  {
    name: "Hutchins BBQ",
    cuisine: "Steak & Grill",
    pricePerPerson: 35,
    distance: 10.2,
    favorite: true,
    status: "Favorite",
  },
  {
    name: "Tender Smokehouse",
    cuisine: "Steak & Grill",
    pricePerPerson: 30,
    distance: 5.9,
    favorite: true,
    status: "Favorite",
  },
  {
    name: "Chili's Grill & Bar",
    cuisine: "Steak & Grill",
    pricePerPerson: 22,
    distance: 2,
    favorite: false,
    status: "Keep",
  },
  {
    name: "Outback Steakhouse",
    cuisine: "Steak & Grill",
    pricePerPerson: 30,
    distance: 3,
    favorite: false,
    status: "Keep",
  },
  {
    name: "Texas Roadhouse",
    cuisine: "Steak & Grill",
    pricePerPerson: 30,
    distance: 4,
    favorite: false,
    status: "Keep",
  },
  {
    name: "1902 Restaurant",
    cuisine: "Steak & Grill",
    pricePerPerson: 45,
    distance: 2,
    favorite: false,
    status: "Don't know it",
  },
  {
    name: "Trick Rider",
    cuisine: "Steak & Grill",
    pricePerPerson: 45,
    distance: 2,
    favorite: false,
    status: "Don't know it",
  },

  {
    name: "The Brass Tap",
    cuisine: "American",
    pricePerPerson: 25,
    distance: 2,
    favorite: false,
    status: "Keep",
  },
  {
    name: "Culver's",
    cuisine: "American",
    pricePerPerson: 15,
    distance: 3,
    favorite: false,
    status: "Keep",
  },
  {
    name: "Nerdvana",
    cuisine: "American",
    pricePerPerson: 28,
    distance: 11,
    favorite: false,
    status: "Keep",
  },
  {
    name: "Panera Bread",
    cuisine: "American",
    pricePerPerson: 16,
    distance: 3,
    favorite: false,
    status: "Keep",
  },
  {
    name: "Raising Cane's Chicken Fingers",
    cuisine: "American",
    pricePerPerson: 15,
    distance: 4,
    favorite: false,
    status: "Keep",
  },
  {
    name: "The Gin",
    cuisine: "American",
    pricePerPerson: 30,
    distance: 2,
    favorite: false,
    status: "Keep",
  },
  {
    name: "Voodoo Brewing Co. - Frontier",
    cuisine: "American",
    pricePerPerson: 25,
    distance: 2,
    favorite: false,
    status: "Keep",
  },
  {
    name: "Urban Cookhouse",
    cuisine: "American",
    pricePerPerson: 25,
    distance: 3,
    favorite: false,
    status: "Don't know it",
  },

  {
    name: "Domino's Pizza",
    cuisine: "Pizza",
    pricePerPerson: 18,
    distance: 2,
    favorite: false,
    status: "Keep",
  },
  {
    name: "Hideaway Pizza",
    cuisine: "Pizza",
    pricePerPerson: 22,
    distance: 12,
    favorite: false,
    status: "Keep",
  },
  {
    name: "Jet's Pizza",
    cuisine: "Pizza",
    pricePerPerson: 20,
    distance: 11,
    favorite: false,
    status: "Keep",
  },
  {
    name: "KillA Pie",
    cuisine: "Pizza",
    pricePerPerson: 20,
    distance: 2,
    favorite: false,
    status: "Keep",
  },
  {
    name: "Marco's Pizza",
    cuisine: "Pizza",
    pricePerPerson: 18,
    distance: 3,
    favorite: false,
    status: "Keep",
  },
  {
    name: "Palio's Pizza Cafe",
    cuisine: "Pizza",
    pricePerPerson: 20,
    distance: 2,
    favorite: false,
    status: "Keep",
  },
  {
    name: "Pizza Hut",
    cuisine: "Pizza",
    pricePerPerson: 18,
    distance: 2,
    favorite: false,
    status: "Keep",
  },
]